### ISSUE TITLE
flickr module broken

### ISSUE THREAD

**Issue by thesle3p** [woj-ciech/kamerka#16]
when I try and run the flickr module I get the following error
```
python kamerka.py --lat 37.8368723 --lon -122.2645793 --flickr
              o#######o
            o###########o
            o#############o
            #################
            ######  \########o
           #;^ _^,/---\#####!
           ,` /^_ .-~^~-.__\#
          /    ^\/,,@@@,, ;|
         |      \!!@@@@@!! ^,
        #.    .\; '9@@@P'   ^,
        ###./^ ----,_^^      /@-._
                      ^--._,o@@@@@@
                         ^;@@@@@@@@@
                           ^-;@@@@
ꓘamerka 2.0 (FIST) - Build interactive map of cameras, tweets and photos
medium.com/@woj-ciech github.com/woj_ciech

python kamerka.py -h
Example: python kamerka.py --lat "37.235 --lon 115.811111" --dark --twitter --camera --printer
Stay Gold Deli, 51st Street, Temescal, Oakland, Alameda County, California, 94609, USA
----------------Flickr----------------
Found 299825 result(s)
Bobbert #45 .45 in 37.861150,-122.260559
Julia's, Berkeley City Club, Berkeley, California in 37.867694,-122.262670
Art & Soul Festival in 37.805071,-122.271652
Golden leaves. in 37.800080,-122.269173
Sunset Stroll in 37.781778,-122.309546
sunset 02dec2018 3/3 in 37.884400,-122.315370
sunset 02dec2018 2/3 in 37.884400,-122.315370
sunset 02dec2018 1/3 in 37.884436,-122.315395
Abstract Table in 37.810447,-122.266764
I Don't Know Where it Ends in 37.834377,-122.238312
The Wolf, Oakland, California in 37.824563,-122.255006
Fieldwork in 37.881434,-122.302281
Julia's, Berkeley City Club, Berkeley, California in 37.867508,-122.262798
Contained in 37.788802,-122.309306
INSALATA DI BURRATA in 37.840316,-122.251545
The Wolf, Oakland, California in 37.824652,-122.255106
Vanessa annabella in 37.892991,-122.305405
The low road in 37.898147,-122.305737
Traceback (most recent call last):
  File "kamerka.py", line 434, in <module>
    flickr_results = flickr_query(lat, lon)
  File "kamerka.py", line 199, in flickr_query
    'latitude'] + Fore.RESET + ',' + Fore.LIGHTYELLOW_EX + photo['longitude'] + Fore.RESET
TypeError: coercing to Unicode: need string or buffer, int found

```

**Comment by woj-ciech** [comment]
Should work now --> [https://github.com/woj-ciech/kamerka/commit/f2fa197b44347999d7a7230674b7330d6891d21a](https://github.com/woj-ciech/kamerka/commit/f2fa197b44347999d7a7230674b7330d6891d21a)
However it hasn't been tested yet

**Comment by thesle3p** [comment]
still getting the Traceback (most recent call last):

```

  File "kamerka.py", line 436, in <module>
    draw_map(flickr_results, lat, lon, 'flickr')
  File "kamerka.py", line 355, in draw_map
    str_coordinates = flickr_photo['latitude'] + ',' +
flickr_photo['longitude']
TypeError: unsupported operand type(s) for +: 'int' and 'str

```

**Comment by woj-ciech** [comment]
In first case, Flickr returns photo with latitude and longitude 0, which should not happen, I don't know why this photo was in results. I've added exception.
But second one is my stupid mistake :) 
Try now [https://github.com/woj-ciech/kamerka/commit/72b3796ceb7ab3e5e85afbc4e1e0784f18b6ec76](https://github.com/woj-ciech/kamerka/commit/72b3796ceb7ab3e5e85afbc4e1e0784f18b6ec76)
