### ISSUE TITLE
ImportError: cannot import name uses_netloc

### ISSUE THREAD

**Issue by Orisbaum** [woj-ciech/kamerka#17]
Hey! 
when I try to run the script (after installing all the dependencies) on my machine Mojave MacBook Pro PyCharm
I get:
Traceback (most recent call last):
  File "/Users/lol/Library/Preferences/PyCharm2018.2/scratches/scratch.py", line 3, in <module>
    import folium
  File "/Library/Python/2.7/site-packages/folium/__init__.py", line 23, in <module>
    from folium.features import (
  File "/Library/Python/2.7/site-packages/folium/features.py", line 17, in <module>
    from folium.folium import Map
  File "/Library/Python/2.7/site-packages/folium/folium.py", line 16, in <module>
    from folium.map import FitBounds
  File "/Library/Python/2.7/site-packages/folium/map.py", line 15, in <module>
    from folium.utilities import _validate_coordinates, camelize, get_bounds
  File "/Library/Python/2.7/site-packages/folium/utilities.py", line 14, in <module>
    from six.moves.urllib.parse import urlparse, uses_netloc, uses_params, uses_relative
ImportError: cannot import name uses_netloc

would love your help with solving this issue :)
thanks in advance!

**Comment by woj-ciech** [comment]
Hey. Can you please post exact command that you use?

**Comment by Orisbaum** [comment]
Just running the script from the repo after I've inserted all the relevant keys for the apis.
