### ISSUE TITLE
Hello, please check my mistakes.

### ISSUE THREAD

**Issue by yckj666** [woj-ciech/kamerka#19]
E:\WordCmear\kamerka>python kamerka.py --lat 37.235 --lon 115.811111 --dark --twitter --camera --printer
Fail to import moviepy. Need only for Video upload.
              o#######o
            o###########o
            o#############o
            #################
            ######  \########o
           #;^ _^,/---\#####!
           ,` /^_ .-~^~-.__\#
          /    ^\/,,@@@,, ;|
         |      \!!@@@@@!! ^,
        #.    .\; '9@@@P'   ^,
        ###./^ ----,_^^      /@-._
                      ^--._,o@@@@@@
                         ^;@@@@@@@@@
                           ^-;@@@@
ꓘamerka 2.0 (FIST) - Build interactive map of cameras, tweets and photos
medium.com/@woj-ciech github.com/woj_ciech

python kamerka.py -h
Example: python kamerka.py --lat "37.235 --lon 115.811111" --dark --twitter --camera --printer
Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\geopy\geocoders\base.py", line 344, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1039: The handshake operation timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kamerka.py", line 421, in <module>
    location = geolocator.reverse(coordinates, language='en')
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\geopy\geocoders\osm.py", line 369, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\geopy\geocoders\base.py", line 367, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out

------------------------------------------------------------------------

The version of the package is downloaded as you provide it.

python kamerka.py --lat 37.235 --lon 115.811111 --dark --twitter --camera --printer

**Comment by ghost** [comment]
same "Fail to import moievpy" error problem :(
any solve ?
