### ISSUE TITLE
KeyError: 'ports'

### ISSUE THREAD

**Issue by VoidSec** [woj-ciech/kamerka#22]
Hi, I was testing the tool with the following parameters: ./kamerka.py --country IT
I've enabled shodan and google street view api

```Found Street View photo for 44.6999,8.0347
Traceback (most recent call last):
  File "./kamerka.py", line 610, in <module>
    ics_coordinates = draw_map(shodan_ics_results, "ics")
  File "./kamerka.py", line 505, in draw_map
    additional_ports = get_host_info(ip)
  File "./kamerka.py", line 169, in get_host_info
    return req_json['ports']
KeyError: 'ports'
```

If you need other info regarding my setup please let me know

**Comment by woj-ciech** [comment]
Yea, right, some of the host does not have additional ports. Should be fine now --> https://github.com/woj-ciech/kamerka/commit/82b42976a707413e2567eedfff6acac16790a5b3 
I saw that you used my tool in your article. Great job.

**Comment by VoidSec** [comment]
Yeah, your tool was extremely helpful to map out a nice subset.
Thank you for the tool. :)

Tomorrow I will check the fix and close the issue if everithing runs smoothly.
