### ISSUE TITLE
Instagram module broken

### ISSUE THREAD

**Issue by thesle3p** [woj-ciech/kamerka#27]
Whenever I try and run the instagram module I get this error after it gathers the photos

```
Traceback (most recent call last):
  File "./kamerka.py", line 835, in <module>
    insta_results = instagram_query(lat, lon)
  File "./kamerka.py", line 298, in instagram_query
    coordinates.append(float(venue['lat']))
KeyError: 'lat'
```

**Comment by thesle3p** [comment]
anyone else have this issue or found a fix?
